### ISSUE TITLE
Map Reactivity Fixes

### ISSUE THREAD

**Issue by nmde** [nmde/photo-manager#16]
The embedded map is not thoroughly reactive to changes made on the locations page. For example, changing a layer's color does not change the colors of the map elements until the page is reloaded.
The following behavior should be responsive:
- Deleting places and shapes
- Changing layer colors
- Moving places and shapes between layers
- Changing place icons

**Comment by nmullane** [comment]
- changing layer colors done

**Comment by nmullane** [comment]
all behaviors are responsive
